### ISSUE TITLE
Presentation peer review

### ISSUE THREAD

**Issue by Bolajiadewal3** [INFO-526-S24/project-01-The-Power-of-the-Voters#6]
The following is the peer review of the Presentation proposal by [name of team completing peer review]. The team members that participated in this review are

-Srinivasan Poonkundran - @kANNISTER
-Tanya Evita George - @tanyageorge
-Mobolaji Adewale - @Bolajiadewal3
-Rohit Vatsava Kalakala - @rohit-vatsava
-Noureen Mithaigar- @musketer26

Review

- Content: Is the research question well designed and is the data being used relevant to the research question?

The research questions are well-designed and give a specific time frame, and the analysis to be provided is stated alongside the question. The data is relevant to the questions as it aims to provide voting information which is relevant to voting outcomes.

- Content: Did the team use appropriate visualizations and did they interpret them accurately?

The maps used are entirely relevant to the dataset and are interpreted correctly to allow for good conclusions to be made. The voting methods question uses good use of colour and makes sure to use colours that are already known to represent the democratic and republican parties: blue and red.

- Creativity and Critical Thought: Is the project carefully thought out? Are the limitations carefully considered? Does it appear that time and effort went into the planning and implementation of the project?

The project has been clearly planned, yet the exact interpretations of the maps are slightly difficult to understand without any text explanation present. The voting methods plot is slightly hard to understand, yet is creatively displayed and faceted. The use of year tabs is creative and helps with understanding.

- Slides: Are the slides well organized, readable, not full of text, featuring figures with legible labels, legends, etc.?

The slides are well produced and use space efficiently, without being clustered with text: however legends could benefit from some additional explanation as to certain colours - like those that are more transparent.

- Professionalism: How well did the team present? Does the presentation appear to be well practiced? Are they reading off of a script? Did everyone get a chance to say something meaningful about the project?

The team presented well and kept their presentation concise and well within the time limit, everyone managed to contribute to the presentation vocally.

**Comment by tezz-us** [comment]
Thankyou for your feedback !!
